language: "en"

pipeline:
- name: "HFTransformersNLP"
- name: "LanguageModelTokenizer"
- name: "LanguageModelFeaturizer"
- name: "SklearnIntentClassifier"
- name: "DIETClassifier"
  intent_classification: False

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FormPolicy"
