language: "en"

pipeline:
- name: "HFTransformersNLP"
- name: "LanguageModelTokenizer"
- name: "LanguageModelFeaturizer"
- name: "EntitySynonymMapper"
- name: "DIETClassifier"
  intent_classification: False
  epochs: 100
- name: "SklearnIntentClassifier"
###- name: "KeywordIntentClassifier"
