language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "DIETClassifier"
- name: "EntitySynonymMapper"

- name: "SklearnIntentClassifier"
